docker_network:
    name: monitoring_network
    subnet: 172.3.27.0/24
telegraf_config:
  input_plugins:
    - name: docker
      attributes:
        endpoint: "unix:///var/run/docker.sock"  
        gather_services: false
        container_name_include: []
        container_name_exclude: []
        timeout: "5s"
        total: false
  output_plugins:
    - name: file
      attributes:
        files: ["/tmp/telegraf/telegraf.out"]
        rotation_interval: "5m"
        rotation_max_archives: 3
        data_format: "json"